name: easy_web_view_plus
description: A super simple webview for Flutter Web and Mobile
version: 2.0.0
homepage: https://github.com/harris-tiwa/easy_web_view
repository: https://github.com/harris-tiwa/easy_web_view
maintainer: Harris Crosswell
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^2.0.2
  flutter_markdown: ^0.6.6
  markdown: ^4.0.0
  html2md: ^1.2.5
  url_launcher: ^6.0.10
  http: ^0.13.3
  permission_handler: ^8.1.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
